// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetImageBase64(arg1) {
  return window['go']['main']['App']['GetImageBase64'](arg1);
}

export function LoadNote() {
  return window['go']['main']['App']['LoadNote']();
}

export function SaveImage(arg1) {
  return window['go']['main']['App']['SaveImage'](arg1);
}

export function SaveNote(arg1) {
  return window['go']['main']['App']['SaveNote'](arg1);
}

export function ShowAboutDialog() {
  return window['go']['main']['App']['ShowAboutDialog']();
}
