// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetImageBase64(arg1:string):Promise<string>;

export function LoadNote():Promise<string>;

export function SaveImage(arg1:string):Promise<string>;

export function SaveNote(arg1:string):Promise<main.SaveResult>;

export function ShowAboutDialog():Promise<void>;
